---
additional_system_deps:
  - libconfig-simple-perl
  - libyaml-perl
  - libcrypt-ssleay-perl
  - libclass-inspector-perl
  - libsoap-lite-perl
  - libipc-run3-perl
  - libprobe-perl-perl
  - libtest-script-perl
  - libtext-glob-perl
  - libterm-readline-perl-perl
cpan:
  broken_tests:
    - Geo::Weather
    - Net::Google
# This is a whitelist of scripts who are currently allowed to fail
# testing. They should be fixed and then removed from the whitelist.
whitelist:
  - act_fifo
  - act
  - aidle
  - amaroknp
  - apm
  - armeija
  - autoaway
  - autolimit
  - autoopper
  - auto_whois
  - autowhois
  - autowhois_simple
  - away2web
  - away
  - awayproxy
  - babelirc
  - bandwidth
  - beep_beep
  - beep
  - bitlbee_join_notice
  - bitlbee_join_notice-pre-3.0
  - blowjob
  - buf
  - centericq
  - cgrep
  - chanshare
  - clones
  - colorkick
  - connectcmd
  - cron
  - dau
  - dcc_ip
  - dccmove
  - dccself
  - dccstat
  - deliciousurl
  - df
  - dictcomplete
  - dnsspam
  - doc
  - emaildb1.0
  - email_privmsgs
  - eng_no_translate_dpryo
  - exec_clean
  - extaway
  - fakectcp
  - file
  - findbot
  - find
  - fleech
  - friends_peder
  - friends_shasta
  - fserve
  - getop
  - gimmie
  - gsi
  - hddtemp
  - hilightwin
  - hipchat_complete
  - hitcount
  - hlbot
  - hl
  - hostname
  - ignore_log
  - ignoreoc
  - iMPD
  - intjoin
  - irc_chess
  - irccomplete
  - ircgallery
  - ircgmessagenotify
  - irssiBlaster
  - irssiq
  - isdn
  - ixmmsa
  - kblamehost
  - keepnick
  - kicks
  - kill_fake_gets
  - kills
  - l33tmusic
  - lastfm
  - lastspoke
  - licq
  - linkchan
  - listen
  - loadavg
  - localize
  - log2ansi
  - logcompress
  - ls
  - lwho
  - mailcheck_imap
  - mailcheck_mbox_flux
  - mailcheck_pop3_kimmo
  - mail
  - mangle
  - mass_hilight_blocker
  - mkshorterlink
  - monitor
  - mpg123
  - my_beep
  - mysqlurllogger
  - nact
  - newsline
  - nickban
  - nickcolor
  - nicklist
  - nickserv
  - nm
  - noisyquery
  - notes
  - noticemove
  - ogg123
  - oidenty
  - 'on'
  - opnotice
  - orphamp
  - osd
  - page-c0ffee
  - page_reeler
  - pager
  - paste-derwan
  - paste_kimmoke
  - pggb_sound
  - query
  - queryresume
  - quitmsg
  - quitrand
  - quizgr
  - quizmaster-fr
  - quizmaster
  - quiz
  - randaway
  - randname
  - redirect
  - relm
  - remote
  - reorder
  - scriptassist
  - scripthelp
  - scroller
  - servercomplete
  - seti
  - shorturl
  - showhilight
  - sms
  - stocks
  - sysinfo270-irssi
  - sysinfo277-irssi
  - sysinfo_dg
  - sysinfo_juerd
  - sysinfoplus
  - talk
  - thistory
  - timezones
  - title
  - topicsed
  - trackbar
  - tracknick
  - translit
  - tvmusor
  - twprompt
  - twsocials
  - twtopic
  - u
  - uptime
  - urlfeed
  - urlgrab
  - url_log
  - urlplot
  - usercount
  - userhost
  - users
  - version-stat
  - wa
  - watch
  - weather
  - wkb
  - wordcompletition
  - xauth
  - xetra
  - xmms2
  - xmmsinfo
  - xmms
  - xqf
