---
scripts_yaml_keys:
  # required
  - filename
  - version
  - authors
  - contact
  - name
  - description
  - license
  # optional
  - url
  - commands
  - note
  - modules
  # explicit
  - modified
  # special
  - HIDDEN
cpan:
  broken_tests:
    - Geo::Weather
    - Net::Google
  broken_modules:
    - Xmms
    - Xmms::Remote
    - spamcalc::SpamCalc
    - Net::vICQ
# This is a whitelist of scripts who are currently allowed to fail
# testing. They should be fixed and then removed from the whitelist.
whitelist:
  - amaroknp
  - cap_sasl_fail
  - cap_sasl
  - dnsspam
  - idonkey
  - ircgallery
  - irssiq
  - isdn
  - ixmmsa
  - l33tmusic
  - log2ansi
  - trackbar22
  - tvmusor
  - xmmsinfo
